//
// Generated file, do not edit! Created by nedtool 5.4 from PriorityMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PRIORITYMESSAGE_M_H
#define __PRIORITYMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PriorityMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message PriorityMessage
 * {
 *     int priority;
 *     string content;
 * }
 * </pre>
 */
class PriorityMessage : public ::omnetpp::cMessage
{
  protected:
    int priority;
    ::omnetpp::opp_string content;

  private:
    void copy(const PriorityMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PriorityMessage&);

  public:
    PriorityMessage(const char *name=nullptr, short kind=0);
    PriorityMessage(const PriorityMessage& other);
    virtual ~PriorityMessage();
    PriorityMessage& operator=(const PriorityMessage& other);
    virtual PriorityMessage *dup() const override {return new PriorityMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PriorityMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PriorityMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PRIORITYMESSAGE_M_H

